/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pratikum19062025;

/**
 *
 * @author MyBook Z Series
 */
public class MenuMakanan extends javax.swing.JFrame {

    /**
     * Creates new form MenuMakanan
     */
    private MenuUtama utama;
    
    public MenuMakanan() {
        initComponents();
    }
    public MenuMakanan(MenuUtama utama){
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkNasiGoreng = new javax.swing.JCheckBox();
        chkMieGoreng = new javax.swing.JCheckBox();
        chkSateAyam = new javax.swing.JCheckBox();
        chkSoto = new javax.swing.JCheckBox();
        cbNasgor = new javax.swing.JComboBox<>();
        cbMieGoreng = new javax.swing.JComboBox<>();
        cbSateAyam = new javax.swing.JComboBox<>();
        cbSoto = new javax.swing.JComboBox<>();
        txtJumlahNasgor = new javax.swing.JTextField();
        txtJumlahMieGoreng = new javax.swing.JTextField();
        txtJumlahSate = new javax.swing.JTextField();
        txtJumlahSoto = new javax.swing.JTextField();
        txtNasiGoreng = new javax.swing.JTextField();
        txtMieGoreng = new javax.swing.JTextField();
        txtSateAyam = new javax.swing.JTextField();
        txtSoto = new javax.swing.JTextField();
        btnTotalHarga = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKembaliKeMenuUtama = new javax.swing.JButton();
        txtTotalHarga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chkNasiGoreng.setText("Nasi Goreng");
        chkNasiGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNasiGorengActionPerformed(evt);
            }
        });

        chkMieGoreng.setText("Mie Goreng");
        chkMieGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMieGorengActionPerformed(evt);
            }
        });

        chkSateAyam.setText("Sate Ayam");
        chkSateAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSateAyamActionPerformed(evt);
            }
        });

        chkSoto.setText("Soto");
        chkSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSotoActionPerformed(evt);
            }
        });

        cbNasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7" }));
        cbNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNasgorActionPerformed(evt);
            }
        });

        cbMieGoreng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7" }));
        cbMieGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMieGorengActionPerformed(evt);
            }
        });

        cbSateAyam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7" }));
        cbSateAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSateAyamActionPerformed(evt);
            }
        });

        cbSoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7" }));
        cbSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSotoActionPerformed(evt);
            }
        });

        txtJumlahNasgor.setText("0");
        txtJumlahNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahNasgorActionPerformed(evt);
            }
        });

        txtJumlahMieGoreng.setText("0");
        txtJumlahMieGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahMieGorengActionPerformed(evt);
            }
        });

        txtJumlahSate.setText("0");

        txtJumlahSoto.setText("0");

        txtNasiGoreng.setText("0");

        txtMieGoreng.setText("0");
        txtMieGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMieGorengActionPerformed(evt);
            }
        });

        txtSateAyam.setText("0");

        txtSoto.setText("0");

        btnTotalHarga.setText("Total Harga");
        btnTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalHargaActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKembaliKeMenuUtama.setText("Kembali ke menu utama");
        btnKembaliKeMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliKeMenuUtamaActionPerformed(evt);
            }
        });

        txtTotalHarga.setText("0");

        jLabel1.setText("MENU MAKANAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkMieGoreng)
                    .addComponent(chkNasiGoreng)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkSoto)
                        .addComponent(chkSateAyam)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtMieGoreng, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(txtSateAyam)
                    .addComponent(txtSoto)
                    .addComponent(txtNasiGoreng))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMieGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJumlahMieGoreng)
                            .addComponent(txtJumlahNasgor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSateAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJumlahSate, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(txtJumlahSoto))))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addGap(47, 47, 47)
                .addComponent(btnTotalHarga)
                .addGap(18, 18, 18)
                .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnKembaliKeMenuUtama))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNasiGoreng)
                    .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlahNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMieGoreng)
                    .addComponent(cbMieGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlahMieGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMieGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSateAyam)
                    .addComponent(cbSateAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlahSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSateAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSoto)
                    .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlahSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTotalHarga)
                        .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKembaliKeMenuUtama)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahNasgorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahNasgorActionPerformed

    private void chkSateAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateAyamActionPerformed
        // TODO add your handling code here:
        txtSateAyam.setText("15000");
    }//GEN-LAST:event_chkSateAyamActionPerformed

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
        // TODO add your handling code here:
        txtSoto.setText("20000");
    }//GEN-LAST:event_chkSotoActionPerformed

    private void txtMieGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMieGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMieGorengActionPerformed

    private void txtJumlahMieGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahMieGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahMieGorengActionPerformed

    private void btnKembaliKeMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliKeMenuUtamaActionPerformed
        // TODO add your handling code here:
        String total = txtTotalHarga.getText();
        utama.setTotMakanan(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliKeMenuUtamaActionPerformed

    private void chkNasiGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasiGorengActionPerformed
        // TODO add your handling code here:
        txtNasiGoreng.setText("15000");
    }//GEN-LAST:event_chkNasiGorengActionPerformed

    private void chkMieGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMieGorengActionPerformed
        // TODO add your handling code here:
        txtMieGoreng.setText("10000");
    }//GEN-LAST:event_chkMieGorengActionPerformed

    private void cbNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNasgorActionPerformed
        // TODO add your handling code here:
        int jml = (int)cbNasgor.getSelectedIndex();
        double harga = Double.parseDouble(txtNasiGoreng.getText());
        double total = jml*harga;
        txtJumlahNasgor.setText(Double.toString(total));
    }//GEN-LAST:event_cbNasgorActionPerformed

    private void cbMieGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMieGorengActionPerformed
        // TODO add your handling code here:
        int jml = (int)cbMieGoreng.getSelectedIndex();
        double harga = Double.parseDouble(txtMieGoreng.getText());
        double total = jml*harga;
        txtJumlahMieGoreng.setText(Double.toString(total));
    }//GEN-LAST:event_cbMieGorengActionPerformed

    private void cbSateAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSateAyamActionPerformed
        // TODO add your handling code here:
        int jml = (int)cbSateAyam.getSelectedIndex();
        double harga = Double.parseDouble(txtSateAyam.getText());
        double total = jml*harga;
        txtJumlahSate.setText(Double.toString(total));
    }//GEN-LAST:event_cbSateAyamActionPerformed

    private void cbSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSotoActionPerformed
        // TODO add your handling code here:
        int jml = (int)cbSoto.getSelectedIndex();
        double harga = Double.parseDouble(txtSoto.getText());
        double total = jml*harga;
        txtJumlahSoto.setText(Double.toString(total));
    }//GEN-LAST:event_cbSotoActionPerformed

    private void btnTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalHargaActionPerformed
        // TODO add your handling code here:
        double nasgor = Double.parseDouble(txtJumlahNasgor.getText());
        double migor = Double.parseDouble(txtJumlahMieGoreng.getText());
        double sate = Double.parseDouble(txtJumlahSate.getText());
        double soto = Double.parseDouble(txtJumlahSoto.getText());
        double total = nasgor+migor+sate+soto;
        txtTotalHarga.setText(String.valueOf(total));
     
    }//GEN-LAST:event_btnTotalHargaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtNasiGoreng.setText("0");
        txtMieGoreng.setText("0");
        txtSateAyam.setText("0");
        txtSoto.setText("0");
        txtTotalHarga.setText("0");
        cbNasgor.setSelectedIndex(0);
        cbMieGoreng.setSelectedIndex(0);
        cbSateAyam.setSelectedIndex(0);
        cbSoto.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembaliKeMenuUtama;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotalHarga;
    private javax.swing.JComboBox<String> cbMieGoreng;
    private javax.swing.JComboBox<String> cbNasgor;
    private javax.swing.JComboBox<String> cbSateAyam;
    private javax.swing.JComboBox<String> cbSoto;
    private javax.swing.JCheckBox chkMieGoreng;
    private javax.swing.JCheckBox chkNasiGoreng;
    private javax.swing.JCheckBox chkSateAyam;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtJumlahMieGoreng;
    private javax.swing.JTextField txtJumlahNasgor;
    private javax.swing.JTextField txtJumlahSate;
    private javax.swing.JTextField txtJumlahSoto;
    private javax.swing.JTextField txtMieGoreng;
    private javax.swing.JTextField txtNasiGoreng;
    private javax.swing.JTextField txtSateAyam;
    private javax.swing.JTextField txtSoto;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
