/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pratikum19062025;

/**
 *
 * @author MyBook Z Series
 */
public class MenuMinuman extends javax.swing.JFrame {

    /**
     * Creates new form MenuMinuman
     */
    private MenuUtama utama;
     
    public MenuMinuman() {
        initComponents();
    }
     public MenuMinuman(MenuUtama utama){
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkJus = new javax.swing.JCheckBox();
        chkMatcha = new javax.swing.JCheckBox();
        chkTeh = new javax.swing.JCheckBox();
        chkGreen = new javax.swing.JCheckBox();
        txtJus = new javax.swing.JTextField();
        txtMatcha = new javax.swing.JTextField();
        txtTeh = new javax.swing.JTextField();
        txtGreen = new javax.swing.JTextField();
        cbJus = new javax.swing.JComboBox<>();
        cbMatcha = new javax.swing.JComboBox<>();
        cbTeh = new javax.swing.JComboBox<>();
        cbGreen = new javax.swing.JComboBox<>();
        txtTotJeruk = new javax.swing.JTextField();
        txtTotMatcha = new javax.swing.JTextField();
        txtTotTeh = new javax.swing.JTextField();
        txtTotGreen = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnTotHarga = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        txtTotHarga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chkJus.setText("Jus Jeruk");
        chkJus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJusActionPerformed(evt);
            }
        });

        chkMatcha.setText("Matcha");
        chkMatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMatchaActionPerformed(evt);
            }
        });

        chkTeh.setText("Teh Es");
        chkTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTehActionPerformed(evt);
            }
        });

        chkGreen.setText("Green Tea");
        chkGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGreenActionPerformed(evt);
            }
        });

        txtJus.setText("0");
        txtJus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJusActionPerformed(evt);
            }
        });

        txtMatcha.setText("0");
        txtMatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatchaActionPerformed(evt);
            }
        });

        txtTeh.setText("0");
        txtTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTehActionPerformed(evt);
            }
        });

        txtGreen.setText("0");
        txtGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGreenActionPerformed(evt);
            }
        });

        cbJus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", " ", " ", " ", " ", " " }));
        cbJus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJusActionPerformed(evt);
            }
        });

        cbMatcha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", " ", " " }));
        cbMatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMatchaActionPerformed(evt);
            }
        });

        cbTeh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", " " }));
        cbTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTehActionPerformed(evt);
            }
        });

        cbGreen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", " " }));
        cbGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGreenActionPerformed(evt);
            }
        });

        txtTotJeruk.setText("0");
        txtTotJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotJerukActionPerformed(evt);
            }
        });

        txtTotMatcha.setText("0");

        txtTotTeh.setText("0");

        txtTotGreen.setText("0");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnTotHarga.setText("TotalHarga");
        btnTotHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotHargaActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali Ke Menu Utama");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        txtTotHarga.setText("0");

        jLabel1.setText("MENU MINUMAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkJus)
                            .addComponent(chkMatcha)
                            .addComponent(chkTeh)
                            .addComponent(chkGreen))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTeh)
                            .addComponent(txtGreen)
                            .addComponent(txtMatcha)
                            .addComponent(txtJus, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(cbJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbMatcha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbTeh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbGreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnTotHarga)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTotTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotMatcha)
                                    .addComponent(txtTotJeruk, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                                .addComponent(txtTotGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnKembali)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkJus)
                    .addComponent(txtJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMatcha)
                    .addComponent(txtMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTeh)
                    .addComponent(txtTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkGreen)
                    .addComponent(txtGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnTotHarga)
                    .addComponent(txtTotHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGreenActionPerformed
        // TODO add your handling code here:
        int jml = (int)cbGreen.getSelectedIndex();
        double harga = Double.parseDouble(txtGreen.getText());
        double total = jml*harga;
        txtTotGreen.setText(Double.toString(total));
    }//GEN-LAST:event_cbGreenActionPerformed

    private void chkJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJusActionPerformed
        // TODO add your handling code here:
          txtJus.setText("10000");
    }//GEN-LAST:event_chkJusActionPerformed

    private void chkMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMatchaActionPerformed
        // TODO add your handling code here:
        txtMatcha.setText("15000");
    }//GEN-LAST:event_chkMatchaActionPerformed

    private void txtTotJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotJerukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotJerukActionPerformed

    private void txtJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJusActionPerformed

    private void btnTotHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotHargaActionPerformed
        // TODO add your handling code here:
        double jus = Double.parseDouble(txtTotJeruk.getText());
        double matcha = Double.parseDouble(txtTotMatcha.getText());
        double teh = Double.parseDouble(txtTotTeh.getText());
        double green = Double.parseDouble(txtTotGreen.getText());
        double total = jus+matcha+teh+green;
        txtTotHarga.setText(String.valueOf(total));
    }//GEN-LAST:event_btnTotHargaActionPerformed

    private void txtMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatchaActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_txtMatchaActionPerformed

    private void txtTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTehActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtTehActionPerformed

    private void txtGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGreenActionPerformed

    private void cbJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJusActionPerformed
        // TODO add your handling code here:
        int jml = (int)cbJus.getSelectedIndex();
        double harga = Double.parseDouble(txtJus.getText());
        double total = jml*harga;
        txtTotJeruk.setText(Double.toString(total));
    }//GEN-LAST:event_cbJusActionPerformed

    private void cbMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMatchaActionPerformed
        // TODO add your handling code here:
        int jml = (int)cbMatcha.getSelectedIndex();
        double harga = Double.parseDouble(txtMatcha.getText());
        double total = jml*harga;
        txtTotMatcha.setText(Double.toString(total));
    }//GEN-LAST:event_cbMatchaActionPerformed

    private void cbTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTehActionPerformed
        // TODO add your handling code here:
        int jml = (int)cbTeh.getSelectedIndex();
        double harga = Double.parseDouble(txtTeh.getText());
        double total = jml*harga;
        txtTotTeh.setText(Double.toString(total));
    }//GEN-LAST:event_cbTehActionPerformed

    private void chkTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTehActionPerformed
        // TODO add your handling code here:
           txtTeh.setText("5000");
    }//GEN-LAST:event_chkTehActionPerformed

    private void chkGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGreenActionPerformed
        // TODO add your handling code here:
         txtGreen.setText("20000");
    }//GEN-LAST:event_chkGreenActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        String total = txtTotHarga.getText();
        utama.setTotMinuman(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtJus.setText("0");
        txtMatcha.setText("0");
        txtTeh.setText("0");
        txtGreen.setText("0");
        txtTotHarga.setText("0");
        cbJus.setSelectedIndex(0);
        cbMatcha.setSelectedIndex(0);
        cbTeh.setSelectedIndex(0);
        cbGreen.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotHarga;
    private javax.swing.JComboBox<String> cbGreen;
    private javax.swing.JComboBox<String> cbJus;
    private javax.swing.JComboBox<String> cbMatcha;
    private javax.swing.JComboBox<String> cbTeh;
    private javax.swing.JCheckBox chkGreen;
    private javax.swing.JCheckBox chkJus;
    private javax.swing.JCheckBox chkMatcha;
    private javax.swing.JCheckBox chkTeh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtGreen;
    private javax.swing.JTextField txtJus;
    private javax.swing.JTextField txtMatcha;
    private javax.swing.JTextField txtTeh;
    private javax.swing.JTextField txtTotGreen;
    private javax.swing.JTextField txtTotHarga;
    private javax.swing.JTextField txtTotJeruk;
    private javax.swing.JTextField txtTotMatcha;
    private javax.swing.JTextField txtTotTeh;
    // End of variables declaration//GEN-END:variables
}
