/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasKelasPengganti;

import javax.swing.JOptionPane;

/**
 *
 * @author MyBook Z Series
 */
public class pembayaranToko extends javax.swing.JFrame {

    /**
     * Creates new form pembayaranToko
     */
    public pembayaranToko() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelKedai = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelTotPembayaran = new javax.swing.JLabel();
        labelJumlah = new javax.swing.JLabel();
        labelDiskon = new javax.swing.JLabel();
        labelTotPembelian = new javax.swing.JLabel();
        labelUang = new javax.swing.JLabel();
        labelUangKembalian = new javax.swing.JLabel();
        txtTotPembayaran = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        txtTotPembelian = new javax.swing.JTextField();
        txtUang = new javax.swing.JTextField();
        txtUangKembalian = new javax.swing.JTextField();
        cbPilihBarang = new javax.swing.JComboBox<>();
        labelHarga = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnKembalian = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        cbBayar = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Area1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelKedai.setText("KEDAI RAISA");

        labelNama.setText("Nama Barang");

        labelTotPembayaran.setText("Total Pembayaran");

        labelJumlah.setText("Jumlah");

        labelDiskon.setText("Diskon");

        labelTotPembelian.setText("Total Pembelian");

        labelUang.setText("Uang Pembayaran");

        labelUangKembalian.setText("Uang Kembalian");

        cbPilihBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang", "Pesil", "Buku", "Kotak Pensil", "penghapus", "Penggaris" }));
        cbPilihBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPilihBarangActionPerformed(evt);
            }
        });

        labelHarga.setText("Harga");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnKembalian.setText("Hitung Kembalian");
        btnKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembalianActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        cbBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pembayaran", "Cash", "Transfer", "Qris" }));
        cbBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBayarActionPerformed(evt);
            }
        });

        Area1.setColumns(20);
        Area1.setRows(5);
        Area1.setPreferredSize(new java.awt.Dimension(500, 40));
        jScrollPane2.setViewportView(Area1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTotPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelUang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDiskon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTotPembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelUangKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotPembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDiskon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUangKembalian)
                            .addComponent(txtUang)
                            .addComponent(txtTotPembelian)
                            .addComponent(cbPilihBarang, 0, 1, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(labelHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbBayar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKembalian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(labelKedai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelKedai)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(cbPilihBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHarga)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotPembayaran)
                    .addComponent(txtTotPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJumlah)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiskon)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotPembelian)
                    .addComponent(txtTotPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembalian))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUang)
                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUangKembalian)
                    .addComponent(txtUangKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKeluar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try{
        int harga = Integer.parseInt(txtHarga.getText());
        int jumlah = Integer.parseInt(txtJumlah.getText());
        int total = harga*jumlah;
        txtTotPembelian.setText(Integer.toString(total));
        double diskon = 0;
        if(total>100000)
            diskon = 0.1*total;
        
        double tbayar = total - diskon;
        txtDiskon.setText(Double.toString(diskon));
        txtTotPembayaran.setText(Double.toString(tbayar));
        cbPilihBarang.requestFocusInWindow();
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(this, "Masukan angka valid", "Jumlah error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       txtHarga.setText("");
       txtJumlah.setText("");
       txtTotPembelian.setText("");
       txtDiskon.setText("");
       txtTotPembayaran.setText("");
       txtUang.setText("");
       txtUangKembalian.setText("");
       cbPilihBarang.setSelectedIndex(0);
       cbBayar.setSelectedIndex(0);
       cbPilihBarang.requestFocusInWindow();
    }//GEN-LAST:event_btnResetActionPerformed

    private void cbPilihBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPilihBarangActionPerformed
        int brg = (int) cbPilihBarang.getSelectedIndex();
        switch(brg){
            case 1 : txtHarga.setText("5000");break;
            case 2 : txtHarga.setText("3000");break;
            case 3 : txtHarga.setText("15000");break;
            case 4 : txtHarga.setText("2000");break;
            case 5 : txtHarga.setText("4000");break;
        }
        txtJumlah.requestFocusInWindow();
    }//GEN-LAST:event_cbPilihBarangActionPerformed

    private void btnKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembalianActionPerformed
        try{
        double uang = Double.parseDouble(txtUang.getText());
        double total = Double.parseDouble(txtTotPembayaran.getText());
        
        
        if(uang < total)
            JOptionPane.showMessageDialog(this, "Uang pembayaran Kurang","WARNING",JOptionPane.INFORMATION_MESSAGE);
        else
        {
            Double kembalian = uang-total;
            txtUangKembalian.setText(Double.toString(kembalian));
        }
       
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Masukan angka yang valid","Uang Pembayaran Error", JOptionPane.ERROR_MESSAGE);
        }
        Area1.setEditable(false);
        Area1.append("Terima Kasih Telah Berbelanja di Toko Kami.");
    
    }//GEN-LAST:event_btnKembalianActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this, "Apakah ingin keluar", "Peringatan", JOptionPane.YES_NO_OPTION);
        if(pilihan == JOptionPane.YES_NO_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void cbBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBayarActionPerformed
        txtUang.requestFocusInWindow();
    }//GEN-LAST:event_cbBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaranToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaranToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaranToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaranToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaranToko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area1;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKembalian;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbBayar;
    private javax.swing.JComboBox<String> cbPilihBarang;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDiskon;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelKedai;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTotPembayaran;
    private javax.swing.JLabel labelTotPembelian;
    private javax.swing.JLabel labelUang;
    private javax.swing.JLabel labelUangKembalian;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTotPembayaran;
    private javax.swing.JTextField txtTotPembelian;
    private javax.swing.JTextField txtUang;
    private javax.swing.JTextField txtUangKembalian;
    // End of variables declaration//GEN-END:variables
}
