/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasKelasPengganti;

import javax.swing.JOptionPane;

/**
 *
 * @author MyBook Z Series
 */
public class PolaPerulangan extends javax.swing.JFrame {

    /**
     * Creates new form PolaPerulangan
     */
    public PolaPerulangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPola = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbPilihPola = new javax.swing.JComboBox<>();
        btnProses = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPola.setText("POLA PERULANGAN");

        cbPilihPola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pola", "Pola 1", "Pola 2", "Pola 3", "Pola 4", "Pola 5", "Pola 6", "Pola 7", " " }));

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        areaOutput.setColumns(20);
        areaOutput.setRows(5);
        jScrollPane1.setViewportView(areaOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(labelPola))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbPilihPola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(130, 130, 130)
                                        .addComponent(btnProses))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4))
                                            .addComponent(txtA, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset)
                            .addComponent(btnKeluar))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPola)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPilihPola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProses)
                    .addComponent(btnReset))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKeluar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
      try{
       int a = Integer.parseInt(txtA.getText());
       int b = Integer.parseInt(txtB.getText());
       int pil = (int) cbPilihPola.getSelectedIndex();
       
       StringBuilder pola = new StringBuilder("Tampilkan Pola \n\n");
       
       
       switch(pil){
           case 1 : for(int i=1;i<=a;i++){
                        for(int j=1;j<=b;j++){
                            pola.append(" * ");
                        }
                        pola.append("\n");
           }
           break;
           case 2 : for (int i = a; i >= 1; i--) {
                        for (int j = 1; j <= b; j++) {
                            if (j <= i) {
                                 pola.append(" "+(i * j)+" "); 
                            } else {
                                pola.append("    "); 
                                    }
                            }
                        pola.append("\n");
                }
           break;
           case 3 : for(int i=1;i<=a;i++){
                        for(int j=1;j<=b;j++)
                            pola.append("");
                        
                        {
                            switch (i%4) {
                                case 1:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" # ");
                                    break;
                                case 2:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" 2 ");
                                    break;
                                case 3:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" * ");
                                    break;
                                default:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" - ");
                                    break;
                            }
                        }
                    pola.append("\n");
       }
       break;
           case 4 : char symbol = '*'; 
                     if (b == 1) symbol = '*';
                    else if (b == 2) symbol = '#';
                    else if (b == 3) symbol = '@';
                for (int i = 1; i <= a; i++) {
                        for (int j = 1; j <= a - i; j++) {
                    pola.append(" ");
                    }   
        
                    for (int k = 1; k <= 2 * i - 1; k++) {
                    pola.append(symbol);
                    }
                    pola.append("\n");
                    }
    
                    for (int i = a - 1; i >= 1; i--) {
                        for (int j = 1; j <= a - i; j++) {
                        pola.append(" ");
                    }
        
                    for (int k = 1; k <= 2 * i - 1; k++) {
                        pola.append(symbol);
                    }
                    pola.append("\n");

        }
           break;
           case 5 : for (int i = 1; i <= a; i++) {
                    for (int j = 1; j <= b; j++) {
                        if (i == 1 || j == 1 || i == j) {
                            pola.append("0 ");
                        } else {
                            pola.append("*  ");
                        }
                    }
                    pola.append("\n");
       }
           break;
           case 6 : for(int i=1;i<=a;i++) {
                    for(int j=b;j>=i;j--){
                        if(i==a || j==b || j==i)
                        {
                         pola.append(" * ");
                        }
                        else
                         {
                        pola.append("   ");
                        }

                    }
                    pola.append("\n");
           }
                    for(int i=2;i<=a;i++) {
                        for(int j=1;j<=i;j++){
                            if(j==1 || j==i)
                                {
                                pola.append(" * ");
                                }
                            else
                                {
                                 pola.append("  ");
                                }

                    }
                    pola.append("\n");
    }
            break;
           default : for (int i = 1; i <= a; i++) {
                    for (int j = 1; j <= b; j++) {
                        if (i == 1 || j == (b + 1) / 2) {
                            pola.append("T ");
                        } else {
                            pola.append("  ");
                        }
                    }
                    pola.append("\n");
           }
           break;
                    
       }
       areaOutput.setText(pola.toString());
       }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Masukan angka valid ","Input Error",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this, "Apakah ingin keluar", "Peringatan", JOptionPane.YES_NO_OPTION);
        if(pilihan == JOptionPane.YES_NO_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
         
        txtA.setText("");
        txtB.setText("");
        cbPilihPola.setSelectedIndex(0);
        areaOutput.setText("");
    }//GEN-LAST:event_btnResetActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolaPerulangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaOutput;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbPilihPola;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPola;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    // End of variables declaration//GEN-END:variables
}
