/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum12062025;

import javax.swing.JOptionPane;

/**
 *
 * @author MyBook Z Series
 */
public class PolaPerulangan2 extends javax.swing.JFrame {

    /**
     * Creates new form PolaPerulangan2
     */
    public PolaPerulangan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        cbPilihPola = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        areaHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbPilihPola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masukan Pola", "Pola 1", "Pola 2", "Pola 3", "Pola 4", " " }));

        btnProses.setText("PROSES");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtA)
                            .addComponent(txtB)
                            .addComponent(cbPilihPola, 0, 112, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProses)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel1))
                            .addComponent(areaHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPilihPola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProses))
                .addGap(26, 26, 26)
                .addComponent(areaHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        try{
       int a = Integer.parseInt(txtA.getText());
       int b = Integer.parseInt(txtB.getText());
       int pil = (int) cbPilihPola.getSelectedIndex();
       
       StringBuilder pola = new StringBuilder("Tampilkan Pola \n\n");
       
       
       switch(pil){
           case 1 : for(int i=1;i<=a;i++){
                        for(int j=1;j<=b;j++){
                            pola.append(" * ");
                        }
                        pola.append("\n");
           }
           break;
           case 2 : for (int i = a; i >= 1; i--) {
                        for (int j = 1; j <= b; j++) {
                            if (j <= i) {
                                 pola.append(" "+(i * j)+" "); 
                            } else {
                                pola.append("    "); 
                                    }
                            }
                        pola.append("\n");
                }
           break;
           case 3 : for(int i=1;i<=a;i++){
                        for(int j=1;j<=b;j++)
                            pola.append("");
                        
                        {
                            switch (i%4) {
                                case 1:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" # ");
                                    break;
                                case 2:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" 2 ");
                                    break;
                                case 3:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" * ");
                                    break;
                                default:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" - ");
                                    break;
                            }
                        }
                    pola.append("\n");
       }
       break;
           default : char symbol = '*'; 
                     if (b == 1) symbol = '*';
                    else if (b == 2) symbol = '#';
                    else if (b == 3) symbol = '@';
                for (int i = 1; i <= a; i++) {
                        for (int j = 1; j <= a - i; j++) {
                    pola.append(" ");
                    }   
        
                    for (int k = 1; k <= 2 * i - 1; k++) {
                    pola.append(symbol);
                    }
                    pola.append("\n");
                    }
    
                    for (int i = a - 1; i >= 1; i--) {
                        for (int j = 1; j <= a - i; j++) {
                        pola.append(" ");
                    }
        
                    for (int k = 1; k <= 2 * i - 1; k++) {
                        pola.append(symbol);
                    }
                    pola.append("\n");

        }
           break;
       }
       areaHasil.setText(pola.toString());
       }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Masukan angka valid ","Input Error",JOptionPane.ERROR_MESSAGE);
            }
            
    }//GEN-LAST:event_btnProsesActionPerformed
     //GEN-LAST:event_btnProsesActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        
        txtA.setText("");
        txtB.setText("");
        cbPilihPola.setSelectedIndex(0);
        areaHasil.setText("");
    }//GEN-LAST:event_btnResetActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolaPerulangan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaHasil;
    private javax.swing.JButton btnProses;
    private javax.swing.JComboBox<String> cbPilihPola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    // End of variables declaration//GEN-END:variables
}
